### ISSUE TITLE
Homebridge restart loop

### ISSUE THREAD

**Issue by sam-gabbay** [makleso6/homebridge-broadlink-heater-cooler#14]
When trying to add my AC unit as an accessory, I restart the Homebridge server and get the following error in the logs.

My unit is functional with the AC Freedom app.

[11/17/2020, 1:57:58 PM] Homebridge is running on port 51680.
[11/17/2020, 1:57:59 PM] RangeError [ERR_OUT_OF_RANGE]: The value of "sourceStart" is out of range. It must be <= 0. Received 4
    at _copy (buffer.js:242:11)
    at Buffer.copy (buffer.js:769:12)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-heater-cooler/node_modules/broadlink-aircon-api/src/index.ts:116:19)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[11/17/2020, 1:57:59 PM] Got SIGTERM, shutting down Homebridge...

**Comment by makleso6** [comment]
Hi! Show yours config.json

**Comment by makleso6** [comment]
And what kind of AC do you use?

**Comment by makleso6** [comment]
plz set

**Comment by makleso6** [comment]
try to update package to latest version and find in HB console message 'loop-fix N'

**Comment by sam-gabbay** [comment]
@makleso6 

Updated to 2.2.3 and now have “loop-fix 0” in the console log.

Here is my config file.

{
    "bridge": {
        "name": "Homebridge E9A7",
        "username": "0E:E4:93:B7:E9:A7",
        "port": 51680,
        "pin": "853-15-120"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ],
    "accessories": [
        {
            "name": "AC AUX",
            "mac": "XX:XX:XX:XX:XX:XX",
            "ip": "192.168.X.XXX",
            "accessory": "AirCondionerAccessory"
        }
    ]
}

**Comment by makleso6** [comment]
@sam-gabbay probably in new firmware update of AC, developers made changes.

**Comment by sam-gabbay** [comment]
@makleso6 I sent you an email, would you consider updating for the latest firmware?

**Comment by makleso6** [comment]
@sam-gabbay can you try this?
https://github.com/liaan/broadlink_ac_mqtt
